org.gradle.daemon=false
org.gradle.jvmargs=-Xms512M -Xmx1G -Dfile.encoding=UTF-8 -Dconsole.encoding=UTF-8
org.gradle.configureondemand=false
controllerScene2DVersion=2.3.0
ktxVersion=1.12.1-rc2
graalHelperVersion=2.0.1
universalTweenVersion=6.3.3
enableGraalNative=false
gdxVersion=1.12.1
projectVersion=1.1.0
